config/routes.rb
# -*- encoding : utf-8 -*-
Vietnam::Application.routes.draw do
  root :to => 'home#index'
  get "guides/index"
  get "about_us"      => 'home#about_us', as: :about_us
  get "contact_us"      => 'home#contact_us', as: :contact_us

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :areas, :cities, :albums, :schemes, :sights, :photos, :only => [:show]
  resources :experts, :homestays, only: [:index, :show]
  # resources :orders
  get '/infos', :to => 'infos#index'
  get '/infos/:id', :to => 'infos#show', as: :info
  get '/guides', :to => 'guides#index'
  # get '/girls', :to => 'home#girls', as: :girls
  # get '/girls/:id', :to => 'home#girl', as: :girl


  get 'orders/settle/'                => 'orders#settle', as: :settle_order
  post 'orders/settle/'              => 'orders#set_settle', as: :set_settle
  get 'orders/'                    =>  'orders#index'
  get 'orders/new/'                =>  'orders#new', as: :new_order
  get 'orders/new/pickup'          =>  'orders#new_pickup'
  get 'orders/new/tour'            =>  'orders#new_tour'
  post 'orders'                     =>  'orders#create'
  get 'orders/:id/'                 => 'orders#show',            as: :order
  get 'orders/:id/edit'             =>  'orders#edit',           as: :edit_order
  post 'orders/:id/'                => 'orders#update',          as: :update_order
  delete 'orders/:id/'              => 'orders#destroy',         as: :destroy_order

  get 'wedding'            => 'home#wedding', as: :wedding
  get 'tailor'             => 'home#tailor',  as: :tailor
  get 'charter'            => 'home#charter', as: :charter
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
    @areas = Area.all
    @hot_schemes = Scheme.random[0...4]
    @photos = Photo.horizental.order("RAND()").select {|p| p.album.pictures? }[0...8]
    # @photos = Photo.horizental.select {|p| p.album.pictures? }[0...8]
    @guides = Guide.hot
    @slide_photo = Album.slide.photos.order("RAND()").first
  end

  def about_us
  end

  def contact_us
  end

  def wedding
    @sight = Sight.where(category: 1).first
    if @sight.album
      @gallery_photos = @sight.album.photos
    else
      @gallery_photos = []
    end
  end

  def tailor
    @sight = Sight.where(category: 2).first
    if @sight.album
      @gallery_photos = @sight.album.photos
    else
      @gallery_photos = []
    end
  end

  def girls
    @albums = Album.where(category: 4).order('created_at DESC').page(params[:page]).per(10)
  end

  def girl
    @girl_album = Album.find(params[:id])
  end

  def charter
    @album = Album.where(category: 5).order('created_at DESC').first
    @guides = Guide.charters
  end
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/views/home/about_us.html.erb
<% provide(:title, '关于我们') %>

<div id="pg-about-us" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<%= Site.all.first.about_us.html_safe %>
	</div>

	<%= render 'layouts/footer' %>
</div>

app/views/home/charter.html.erb
<% provide(:title, '旅游包车') %>

<% content_for :scripts do %>
	<%= javascript_include_tag "charter" %>
<% end %>

<div id="pg-charter" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<div class="main">
			<div class="rent">
				<h4 class="section-title">包车信息</h4>
				<div>
					<% if @album.photos.any? %>
					<div id="gallery" class="ad-gallery sight-gallery">
						<div class="ad-image-wrapper">
						</div>
						<div class="ad-controls">
						</div>
						<div class="ad-nav">
							<div class="ad-thumbs">
								<ul class="ad-thumb-list">
									<% @album.photos.each do |p| %>
									<li>
										<a href="<%= p.file.pic %>">
											<%= image_tag p.file.thumb, title: p.name, alt: p.desc %>
										</a>
									</li>
									<% end %>
								</ul>
							</div>
						</div>
					</div>
					<% end %>
				</div>
			</div>

			<% if @guides.any? %>
				<div class="guides">
					<h4 class="section-title">包车手册</h4>
					<dl>
						<% @guides.each do |g| %>
							<dt id="q-<%= g.id %>">
								<%= link_to g.question, "javascript:;" %>
							</dt>
							<dd>
								<%= g.answer.html_safe %>
							</dd>
						<% end %>
					</dl>
				</div>
			<% end %>
		</div>
	</div>

	<%= render 'layouts/footer' %>
</div>

app/views/home/contact_us.html.erb
<% provide(:title, '联系我们') %>

<div id="pg-contact-us" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<%= Site.all.first.contact_us.html_safe %>
	</div>

	<%= render 'layouts/footer' %>
</div>

app/views/home/girl.html.erb
<% provide(:title, @girl_album.name) %>

<div id="pg-girl" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<h2>越南美女图库 - <%= @girl_album.name %></h2>

		<div class="share">
			分享：
			<%= social_share_button_tag("行在越南相册: #{ @girl_album.name }", image: "http://#{ Yetting.domain }:#{ Yetting.port }#{ @girl_album.photos.first.file.pic_with_watermark }") %>
		</div>

		<ul class="girls">
			<% @girl_album.photos.each do |p| %>
				<li>
					<img src="<%= p.file %>" alt="" />
					<p class="name"><%= p.name %></p>
					<% if p.desc %>
						<p class="desc"><%= p.desc %></p>
					<% end %>
				</li>
			<% end %>
		</ul>

		<div class="share">
			分享：
			<%= social_share_button_tag("行在越南相册: #{ @girl_album.name }", image: "http://#{ Yetting.domain }:#{ Yetting.port }#{ @girl_album.photos.first.file.pic_with_watermark }") %>
		</div>
	</div>

	<%= render 'layouts/footer' %>
</div>

app/views/home/girls.html.erb
<% provide(:title, '越南美女图库') %>

<% content_for :scripts do %>
	<%= javascript_include_tag "girls" %>
<% end %>

<div id="pg-girls" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<h2>越南美女图库</h2>
		<ul class="wookmark">
			<% @albums.each do |album| %>
				<li>
					<a href="<%= girl_path(album.id) %>">
						<img src="<%= album.photos.first.file.pic %>" alt="" />
						<p class="name"><%= album.name %></p>
						<% if album.desc %>
							<p class="desc"><%= album.desc %></p>
						<% end %>
					</a>
				</li>
			<% end %>
		</ul>

		<%= paginate @albums %>
	</div>

	<%= render 'layouts/footer' %>
</div>

app/views/home/index.html.erb
<% provide(:title, '首页') %>

<% content_for :scripts do %>
	<%# javascript_include_tag "home" %>
<% end %>

<div id="pg-home" class="container">
	<%= render 'layouts/header' %>

	<div class="content" >
		<%= render "layouts/slides" %>

		<% if false %>
			<div class="intro"></div>
		<% end %>

		<div class="main">
			<div class="map">
				<%= image_tag "map.jpg", alt: "越南地图", class: "img-map", width: "338", height: "700" %>
				<% @areas.each_with_index do |area, index| %>
					<%= link_to image_tag(area.cover.pic_thumb, width: "50", height: "50", alt: area.name), area_path(area), class: "map-area area-#{ area.id - 1 }", title: area.name %>
				<% end %>
			</div>

			<div class="recommend">
				<div class="areas">
					<h4 class="section-title">旅游城市</h4>
					<% @areas.each_with_index do |area, index| %>
						<a class="area<%= cycle(" odd", " even") %>" href="<%= area_path(area) %>">
							<%= image_tag area.cover.thumb.url, alt: area.name %>
							<h6><%= name_by_lang(area) %></h6>
							<p><%= area.desc.truncate(18) %></p>
						</a>
					<% end %>
				</div>

				<div class="hot-schemes-wrap">
					<h4 class="section-title">热门线路</h4>
					<div class="hot-schemes">
						<% @hot_schemes.each do |s| %>
							<a class="hot-scheme" href="<%= scheme_path(s) %>">
								<%= image_tag s.cover.thumb.url, alt: s.name %>
								<h6><%= s.name %></h6>
							</a>
						<% end %>
					</div>
				</div>
				<!--
				<div class="handbook">
				</div> -->
			</div>
		</div>

		<% if @guides.any? %>
			<div class="guides">
				<h4 class="section-title">
					旅行手册
					<%= link_to "更多 »", guides_path, class: "more" %>
				</h4>
				<dl>
					<% @guides.each do |g| %>
						<dt id="q-<%= g.id %>">
							<%= link_to g.question, guides_path(anchor: "q-#{ g.id }") %>
						</dt>
						<dd>
						<%= g.answer.truncate(160, omission: "...#{ link_to('查看全文', guides_path(anchor: 'q-' + g.id.to_s), class: 'more')}").html_safe %>
						</dd>
					<% end %>
				</dl>
			</div>
		<% end %>

		<div class="photos">
			<% if @photos.count == 8 %>
			<h4 class="section-title">越南相册</h4>
			<table>
				<tr>
					<% @photos[0...5].each_with_index do |p, index| %>
						<td class="row-0 <%= "col-#{ index }" %>"<%= " rowspan=2" if index == 2 %>>
							<a href="<%= photo_path(p) %>">
								<%= image_tag index == 2 ? p.file.pic : p.file.thumb %>
								<h6><%= p.name %></h6>
							</a>
						</td>
					<% end %>
				</tr>
				<tr>
					<% @photos[5...8].each_with_index do |p, index| %>
						<td class="row-1 <%= "col-#{ index }" %>"<%= " colspan=2" if index == 2 %>>
							<a href="<%= photo_path(p) %>">
								<%= image_tag p.file.thumb %>
								<h6><%= p.name %></h6>
							</a>
						</td>
					<% end %>
				</tr>
			</table>
			<% end %>
		</div>
	</div>

	<%= render 'layouts/footer' %>
</div>

app/views/home/tailor.html.erb
<% provide(:title, '奥黛定制') %>

<% content_for :scripts do %>
	<%= javascript_include_tag "jquery.easing.1.3" %>
	<%= javascript_include_tag "jquery.timers-1.2" %>
	<%= javascript_include_tag "jquery.galleryview-3.0-dev" %>
	<%= javascript_include_tag "sights" %>
<% end %>

<div id="pg-tailor" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<div class="sight-detail">
			<%# render "layouts/contact_qqs" %>
			<h3 class="sight-title"><%= @sight.name %></h3>

			<% if @gallery_photos.any? %>
			<div id="gallery" class="sight-gallery">
				<ul>
					<% @gallery_photos.each do |p| %>
					<li>
                      <%= image_tag p.file, title: p.name,
                          data: {
							frame: p.file.thumb.url,
                            description: p.desc
                          }
                      %>
					</li>
					<% end %>
				</ul>
			</div>
			<% end %>

			<div class="sight-intro">
				<%= @sight.content.html_safe if @sight.content.html_safe %>
			</div>
		</div>
	</div>

	<%= render 'layouts/footer' %>
</div>

app/views/home/wedding.html.erb
<% provide(:title, '旅游婚纱') %>

<% content_for :scripts do %>
	<%= javascript_include_tag "jquery.easing.1.3" %>
	<%= javascript_include_tag "jquery.timers-1.2" %>
	<%= javascript_include_tag "jquery.galleryview-3.0-dev" %>
	<%= javascript_include_tag "sights" %>
<% end %>

<div id="pg-wedding" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<div class="sight-detail">
			<%# render "layouts/contact_qqs" %>
			<h3 class="sight-title"><%= @sight.name %></h3>

			<% if @gallery_photos.any? %>
			<div id="gallery" class="sight-gallery">
				<ul>
					<% @gallery_photos.each do |p| %>
					<li>
                      <%= image_tag p.file, title: p.name,
                          data: {
							frame: p.file.thumb.url,
                            description: p.desc
                          }
                      %>
					</li>
					<% end %>
				</ul>
			</div>
			<% end %>

			<div class="sight-intro">
				<%= @sight.content.html_safe if @sight.content.html_safe %>
			</div>
		</div>
	</div>

	<%= render 'layouts/footer' %>
</div>