config/routes.rb
# -*- encoding : utf-8 -*-
Vietnam::Application.routes.draw do
  root :to => 'home#index'
  get "guides/index"
  get "about_us"      => 'home#about_us', as: :about_us
  get "contact_us"      => 'home#contact_us', as: :contact_us

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :areas, :cities, :albums, :schemes, :sights, :photos, :only => [:show]
  resources :experts, :homestays, only: [:index, :show]
  # resources :orders
  get '/infos', :to => 'infos#index'
  get '/infos/:id', :to => 'infos#show', as: :info
  get '/guides', :to => 'guides#index'
  # get '/girls', :to => 'home#girls', as: :girls
  # get '/girls/:id', :to => 'home#girl', as: :girl


  get 'orders/settle/'                => 'orders#settle', as: :settle_order
  post 'orders/settle/'              => 'orders#set_settle', as: :set_settle
  get 'orders/'                    =>  'orders#index'
  get 'orders/new/'                =>  'orders#new', as: :new_order
  get 'orders/new/pickup'          =>  'orders#new_pickup'
  get 'orders/new/tour'            =>  'orders#new_tour'
  post 'orders'                     =>  'orders#create'
  get 'orders/:id/'                 => 'orders#show',            as: :order
  get 'orders/:id/edit'             =>  'orders#edit',           as: :edit_order
  post 'orders/:id/'                => 'orders#update',          as: :update_order
  delete 'orders/:id/'              => 'orders#destroy',         as: :destroy_order

  get 'wedding'            => 'home#wedding', as: :wedding
  get 'tailor'             => 'home#tailor',  as: :tailor
  get 'charter'            => 'home#charter', as: :charter
end

app/models/order.rb
# -*- encoding : utf-8 -*-
class Order < ActiveRecord::Base
  attr_accessible :scheme_id, :tour_time, :tour_members_count,
                  :tour_children_free, :tour_children_discount,
                  :tour_adult_count, :status, :category, :cancel_reason

  # status
  # 0: consult
  # 1: ordered
  # 2: cancel
  # 3: payed
  STATUS = %w(
    咨询订单
    待确认订单
    预定成功
    确认发团
    取消发团
    确认支付
    核查完毕
  )

  CATEGORIES = %w(
    旅游订单
    接机订单
  )

  belongs_to :scheme
  has_one :hotel, :dependent => :destroy
  has_one :flight, :dependent => :destroy
  has_many :contacts, :dependent => :destroy

  default_scope order("status ASC, tour_time ASC")

  def tour?
    self.category == 0
  end

  def pickup?
    self.category == 1
  end

  def category_desc
    CATEGORIES[category]
  end

  def status_desc
    STATUS[status]
  end

  # validates :tour_members_count, presence: true
  # validates :status, inclusion: { in: [0,1,2,3], message: "设置的订单状态无效" }
end

# == Schema Information
#
# Table name: orders
#
#  id                     :integer          not null, primary key
#  scheme_id              :integer          not null
#  tour_time              :datetime         not null
#  tour_members_count     :integer          not null
#  tour_adult_count       :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  tour_children_free     :integer          default(0)
#  tour_children_discount :integer          default(0)
#  status                 :integer          not null
#

app/controllers/orders_controller.rb
# -*- encoding : utf-8 -*-
class OrdersController < ApplicationController
  load_and_authorize_resource
  layout "admin"

  before_filter :is_signin

  def index
    @category = (params[:category] || -1).to_i

    if @category < 0
      redirect_to orders_path(category: 0)
      return
    end

    @status = (params[:condition_status] || -1).to_i
    @contact = params[:condition_contact]
    @scheme_id = (params[:condition_scheme] || -1).to_i
    @area_id = (params[:condition_area] || -1).to_i
    @date = params[:condition_date]

    if current_admin_user.receiver?
      @orders = Order.where(status: [1,2,3,4,5,6])
    elsif current_admin_user.agency?
      @orders = Order.where(status: [2,3,4,5,6])
    elsif current_admin_user.admin? or current_admin_user.superuser? or current_admin_user.receiver_manager?
      @orders = Order.where(status: [1,2,3,4,5,6])
    end

    if @category > -1
      @orders = @orders.where(category: @category)
    end

    if @status > -1
      @orders = @orders.where(status: @status)
    end

    if @scheme_id > -1
      @orders = @orders.where(scheme_id: @scheme_id)
    end

    if (@date.nil? or @date.empty?) and (@contact.nil? or @contact.empty?) and (current_admin_user.receiver? or current_admin_user.agency?)
      d = Date.today

      if @category == 0
        time_range = d...(d+3.day)
        @orders = @orders.where(tour_time: time_range)
      elsif @category == 1
        orders = []
        @orders.each do |order|
          if not order.flight.nil? and order.flight.arrive_at >= d and order.flight.arrive_at < (d + 1.day)
            orders.push(order)
          end
        end 

        @orders = orders
      end
    end

    if not @contact.nil? and not @contact.empty?
      q = "%#{ @contact }%"
      @orders = @orders.joins(:contacts).where('name LIKE ? OR chinese_phone LIKE ?', q, q)
    end

    if not @date.nil? and not @date.empty?
      @date = @date.to_date

      if @category == 0
        time_range = @date...(@date+1.day)
        @orders = @orders.where(tour_time: time_range)
      elsif @category == 1
        orders = []
        @orders.each do |order|
          if not order.flight.nil? and order.flight.arrive_at >= @date and order.flight.arrive_at < (@date + 1.day)
            orders.push(order)
          end
        end 

        @orders = orders
      end
    end

    if @area_id > -1
      orders = []
      @orders.each do |order|
        if not order.scheme.nil? and order.scheme.area_id.to_i == @area_id
          orders.push(order)
        end
      end

      @orders = orders
    end
  end

  def show
    @order = Order.find(params[:id])
    @scheme = @order.scheme
    @flight = @order.flight
    @hotel = @order.hotel
  end

  def new
  end

  def new_pickup
    if current_admin_user.receiver?
      @available_status = [1,2]
    elsif current_admin_user.agency?
      @available_status = [3,4,5]
    elsif current_admin_user.admin? or current_admin_user.superuser? or current_admin_user.receiver_manager?
      @available_status = [1,2,3,4,5]
    end
  end

  def new_tour
    if current_admin_user.receiver?
      @available_status = [1,2]
    elsif current_admin_user.agency?
      @available_status = [3,4,5]
    elsif current_admin_user.superuser? or current_admin_user.admin? or current_admin_user.receiver_manager?
      @available_status = [1,2,3,4,5]
    end

  end

  def create
    category = params[:category].to_i
    status = params[:status].to_i

    tour_children_free = params[:tour_children_free].to_i
    tour_children_discount = params[:tour_children_discount].to_i
    tour_adult_count = params[:tour_adult_count].to_i
    tour_members_count = tour_children_free + tour_children_discount + tour_adult_count

    first_contact_name = params[:first_contact_name]
    first_contact_gender = params[:first_contact_gender]
    first_contact_chinese_phone = params[:first_contact_chinese_phone]
    first_contact_vietnamese_phone = params[:first_contact_vietnamese_phone]
    first_contact_passport_number = params[:first_contact_passport_number]
    first_contact_qq = params[:first_contact_qq]
    first_contact_wechat = params[:first_contact_wechat]
    first_contact_weibo = params[:first_contact_weibo]
    first_contact_email = params[:first_contact_email]

    second_contact_name = params[:second_contact_name]
    second_contact_gender = params[:second_contact_gender]
    second_contact_chinese_phone = params[:second_contact_chinese_phone]
    second_contact_vietnamese_phone = params[:second_contact_vietnamese_phone]
    second_contact_passport_number = params[:second_contact_passport_number]
    second_contact_qq = params[:second_contact_qq]
    second_contact_wechat = params[:second_contact_wechat]
    second_contact_weibo = params[:second_contact_weibo]
    second_contact_email = params[:second_contact_email]

    if category == 0
      scheme = params[:scheme]
      tour_time = params[:tour_time].to_datetime
      order = Order.create!(scheme_id: scheme,
                            tour_time: tour_time,
                            tour_members_count: tour_members_count,
                            tour_children_free: tour_children_free,
                            tour_children_discount: tour_children_discount,
                            tour_adult_count: tour_adult_count,
                            status: status,
                            category: category)
    elsif category == 1
      flight_number = params[:flight_number]
      flight_airline = params[:flight_airline]
      flight_arrive_at = params[:flight_arrive_at].to_datetime
      
      order = Order.create!(tour_members_count: tour_members_count,
                            tour_children_free: tour_children_free,
                            tour_children_discount: tour_children_discount,
                            tour_adult_count: tour_adult_count,
                            status: status,
                            category: category)

      flight = Flight.create!(number: flight_number,
                              airline: flight_airline,
                              arrive_at: flight_arrive_at,
                              order_id: order.id)
    end

    first_contact = Contact.create!(name: first_contact_name,
                                    gender: first_contact_gender,
                                    chinese_phone: first_contact_chinese_phone,
                                    vietnamese_phone: first_contact_vietnamese_phone,
                                    passport_number: first_contact_passport_number,
                                    qq: first_contact_qq,
                                    wechat: first_contact_wechat,
                                    weibo: first_contact_weibo,
                                    email: first_contact_email,
                                    order_id: order.id)

    if not second_contact_name.blank? and not second_contact_chinese_phone.blank?
      second_contact = Contact.create!(name: second_contact_name,
                                       gender: second_contact_gender,
                                      chinese_phone: second_contact_chinese_phone,
                                      vietnamese_phone: second_contact_vietnamese_phone,
                                      passport_number: second_contact_passport_number,
                                      qq: second_contact_qq,
                                      wechat: second_contact_wechat,
                                      weibo: second_contact_weibo,
                                      email: second_contact_email,
                                      order_id: order.id)
    end

    hotel_name = params[:hotel_name]
    hotel_address = params[:hotel_address]
    hotel_phone = params[:hotel_phone]

    hotel = Hotel.create!(name: hotel_name,
                          address: hotel_address,
                          phone: hotel_phone,
                          order_id: order.id)

    render json: {
      url: order_path(order)
    }
  end

  def edit
    @order = Order.find(params[:id])
    contacts = @order.contacts
    @first_contact = contacts.first
    @second_contact = contacts.second
    @hotel = @order.hotel

    if current_admin_user.receiver?
      if @order.status == 4
        @available_status = [4,6]
      elsif @order.status == 5
        @available_status = [5,6]
      else
        @available_status = [1,2,4]
      end
    elsif current_admin_user.agency?
      @available_status = [3,4,5]
    elsif current_admin_user.superuser? or current_admin_user.admin? or current_admin_user.receiver_manager?
      @available_status = [1,2,3,4,5,6]
    end

    if @order.tour?
      render 'edit_tour'
    elsif @order.pickup?
      @flight = @order.flight
      render 'edit_pickup'
    end
  end

  def update
    @order = Order.find(params[:id])
    status = params[:status].to_i

    if (@order.status == 4 or @order.status == 5) and current_admin_user.receiver?
      @order.status = status
      @order.save!

      render json: {
        url: order_path(@order.id)
      }
      return
    end

    tour_children_free = params[:tour_children_free].to_i
    tour_children_discount = params[:tour_children_discount].to_i
    tour_adult_count = params[:tour_adult_count].to_i
    tour_members_count = tour_children_free + tour_children_discount + tour_adult_count

    first_contact_name = params[:first_contact_name]
    first_contact_gender = params[:first_contact_gender]
    first_contact_chinese_phone = params[:first_contact_chinese_phone]
    first_contact_vietnamese_phone = params[:first_contact_vietnamese_phone]
    first_contact_passport_number = params[:first_contact_passport_number]
    first_contact_qq = params[:first_contact_qq]
    first_contact_wechat = params[:first_contact_wechat]
    first_contact_weibo = params[:first_contact_weibo]
    first_contact_email = params[:first_contact_email]

app/views/orders/_cancel_reason.html.erb
<% unless @order.status == 4 %>
	<div class="control-group hide" id="reason">
		<label class="control-label" for="cancel-reason">取消原因</label>
		<div class="controls">
			<textarea name="cancel_reason" class="span10" id="cancel-reason" data-validate="required" data-validate-msg="请填写取消订单的原因"></textarea>
		</div>
	</div>
<% end %>

app/views/orders/edit_pickup.html.erb
<% provide(:title, "编辑接机订单") %>

<% content_for :scripts do %>
	<%= javascript_include_tag "order-new" %>
<% end %>

<form action="<%= update_order_path(@order) %>" method="post" class="form form-edit form-horizontal" data-remote novalidate data-confirm="确定要修改此订单吗?">
	<input type="hidden" name="category" value="1" />
	<h1>接机订单</h1>

	<fieldset<%= " disabled" if fieldset_disable? %>>
		<legend>接机信息</legend>
		<div class="control-groups">
			<div class="control-group">
				<label class="control-label" for="">航班号<em>*</em></label>
				<div class="controls">
					<input type="text" name="flight_number" id="" value="<%= @flight.number unless @flight.nil? %>" data-validate="required" data-validate-msg="请填写航班号" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="">航空公司</label>
				<div class="controls">
					<input type="text" name="flight_airline" id="" value="<%= @flight.airline unless @flight.nil? %>" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="">飞机抵达时间<em>*</em></label>
				<div class="controls">
					<div data-behaviour="datetimepicker" class="input-append date">
						<input name="flight_arrive_at" data-format="yyyy-MM-dd hh:mm:ss" readonly type="text" value="<%= @flight.arrive_at.to_s(:db) unless @flight.nil? %>" data-validate="required" data-validate-msg="请填写飞机抵达时间"  />
						<span class="add-on">
							<i class="icon-calendar"></i>
						</span>
					</div>
				</div>
			</div>
		</div>
	</fieldset>

	<fieldset<%= " disabled" if fieldset_disable? %>>
		<legend>人员信息</legend>
<% if false %>
	<div class="control-group">
		<label class="control-label" for="tour-members-count">接机人数<em>*</em></label>
		<div class="controls">
			<input type="number" data-origin="<%= @order.tour_members_count %>" name="tour_members_count" id="tour-members-count" value="<%= @order.tour_members_count %>" data-validate="required;range:1" data-validate-msg="请填写接机人数;请填写一个合理的人数" />
		</div>
	</div>
<% end %>
		<div class="control-group">
			<label class="control-label" for="tour-children-free">免费儿童数<em>*</em></label>
			<div class="controls">
				<input type="number" data-origin="<%= @order.tour_children_free %>" name="tour_children_free" id="tour-children-free" value="<%= @order.tour_children_free %>" data-validate="required;range:0" data-validate-msg="请填写免费儿童数;请填写一个合理的人数" />
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="tour-children-discount">半价儿童数<em>*</em></label>
			<div class="controls">
				<input type="number" data-origin="<%= @order.tour_children_discount %>" name="tour_children_discount" id="tour-children-discount" value="<%= @order.tour_children_discount %>" data-validate="required;range:0" data-validate-msg="请填写半价儿童数;请填写一个合理的人数" />
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="tour-adult-count">成人数<em>*</em></label>
			<div class="controls">
				<input type="number" data-origin="<%= @order.tour_adult_count %>" name="tour_adult_count" id="tour-adult-count" value="<%= @order.tour_adult_count %>" data-validate="required;range:0" data-validate-msg="请填写成人数;请填写一个合理的人数" />
			</div>
		</div>
	</fieldset>

	<div class="row">
		<div class="span-6">
			<fieldset<%= " disabled" if fieldset_disable? %>>
				<legend>第一联系人</legend>
				<%= render partial: 'contact_fieldset', locals: {contact: @first_contact, prefix: 'first'} %>
			</fieldset>
		</div>

		<div class="span-6">
			<fieldset<%= " disabled" if fieldset_disable? %>>
				<legend>第二联系人</legend>
				<%= render partial: 'contact_fieldset', locals: {contact: @second_contact, prefix: 'second'} %>
			</fieldset>
		</div>
	</div>

	<fieldset<%= " disabled" if fieldset_disable? %>>
		<legend>酒店信息</legend>
		<%= render partial: 'hotel_fieldset', locals: {hotel: @hotel} %>
	</fieldset>

	<fieldset>
		<legend>订单状态</legend>
		<div class="control-group">
			<label class="control-label" for="status">订单状态</label>
			<div class="controls">
				<select name="status" id="status" required>
					<% Order::STATUS.each_with_index do |it, idx| %>
						<% unless @available_status.index(idx).nil? %>
						<option value="<%= idx %>"<%= " selected" if idx == @order.status %>><%= it %></option>
						<% end %>
					<% end %>
				</select>
			</div>
		</div>
		<%= render 'cancel_reason' %>
	</fieldset>
	
	<fieldset>
		<div class="control-group">
			<div class="controls">
				<button type="submit" class="btn btn-primary btn-large" data-disable-with="正在保存...">保存订单</button>
				<%= link_to "取消", :back, class: "btn btn-link" %>
			</div>
		</div>
	</fieldset>

</form>

app/views/orders/index.html.erb
<% content_for :scripts do %>
	<%= javascript_include_tag "order-index" %>
<% end %>

<ul id="orderTab" class="nav nav-tabs">
	<% Order::CATEGORIES.each_with_index do |name, category| %>
		<li class="<%= "active" if @category == category %>">
			<%= link_to name, orders_path(category: category) %>
		</li>
	<% end %>
</ul>

<% if @category == 0 %>
	<%= render partial: 'condition', locals: {category:0} %>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>订单状态</th>
				<th>线路</th>
				<th>发团时间</th>
				<th>客户信息</th>
				<th>总人数</th>
				<th>免票人数</th>
				<th>半价人数</th>
				<th>成人数</th>
				<th>酒店信息</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each_with_index do |order, idx| %>
				<% contact = order.contacts.first %>
				<tr>
					<td><%= idx+1 %></td>
					<td><%= order.status_desc %></td>
					<td>
						<% unless order.scheme.nil? %>
							<%= link_to order.scheme.name, scheme_path(order.scheme) %>
						<% end %>
					</td>
					<td><%= order.tour_time.to_date().to_s(:db) %></td>
					<td>
						<% unless contact.nil? %>
						<%= contact.name %> <span class="label label-info"><%= contact.gender_desc %></span> <br />
						<%= contact.chinese_phone %>
						<% end %>
					</td>
					<td><%= order.tour_members_count %></td>
					<td><%= order.tour_children_free %></td>
					<td><%= order.tour_children_discount %></td>
					<td><%= order.tour_adult_count %></td>
					<td>
						<% unless order.hotel.nil? %>
							<%= order.hotel.name %> <%= order.hotel.phone %><br />
							<%= order.hotel.address %>
						<% end %>
					</td>
					<td>
						<%= link_to "详细", order_path(order) %>
						<% if can? :update, order %>
							<%= link_to "编辑", edit_order_path(order) %>
						<% end %>
						<% if can? :destroy, order %>
							<%= link_to "删除", destroy_order_path(order), 
								method: "delete", 
								confirm: "确定要删除此订单?", 
								remote: true, 
								class: "link-destroy-order", 
								data: {
									disable_with: "删除中..."
								} 
							%>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% elsif @category == 1 %>
	<%= render partial: 'condition', locals: {category:1} %>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>订单状态</th>
				<th>航班信息</th>
				<th>抵达时间</th>
				<th>客户信息</th>
				<th>酒店信息</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each_with_index do |order, idx| %>
				<% contact = order.contacts.first %>
				<tr>
					<td><%= idx+1 %></td>
					<td><%= order.status_desc %></td>
					<td>
						<% unless order.flight.nil? %>
							<%= order.flight.airline %> - <%= order.flight.number %><br />
						<% end %>
					</td>
					<td>
						<% unless order.flight.nil? %>
							<%= order.flight.arrive_at.to_s(:db) %>
						<% end %>
					</td>
					<td>
						<% unless contact.nil? %>
							<%= contact.name %> <span class="label label-info"><%= contact.gender_desc %></span> <br />
							<%= contact.chinese_phone %>
						<% end %>
					</td>
					<td>
						<% unless order.hotel.nil? %>
							<%= order.hotel.name %> <%= order.hotel.phone %><br />
							<%= order.hotel.address %>
						<% end %>
					</td>
					<td>
						<%= link_to "详细", order_path(order) %>
						<% if can? :update, order %>
							<%= link_to "编辑", edit_order_path(order) %>
						<% end %>
						<% if can? :destroy, order %>
							<%= link_to "删除", destroy_order_path(order), 
								method: "delete", 
								confirm: "确定要删除此订单?", 
								remote: true, 
								class: "link-destroy-order", 
								data: {
									disable_with: "删除中..."
								} 
							%>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/orders/new.html.erb
<% provide(:title, "创建订单") %>

<% content_for :scripts do %>
	<%= javascript_include_tag "order-new" %>
<% end %>

<div class="btn-group">
	<%= link_to "创建旅行订单", orders_new_tour_path, class: "btn btn-large" %>
	<%= link_to "创建接机订单", orders_new_pickup_path, class: "btn btn-large" %>
</div>
	

app/views/orders/settle.html.erb
<% provide(:title, "订单结算") %>

<% content_for :scripts do %>
	<%= javascript_include_tag "order-settle" %>
<% end %>

<table class="table table-hover">
	<thead>
		<tr>
			<th>日期</th>
			<th>线路</th>
			<th>总人数</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% if @items.count > 0 %>
			<% @items.each do |item| %>
				<tr>
					<td><%= item[:date].to_s(:db) %></td>
					<td><%= item[:scheme].name %></td>
					<td><%= item[:tourist] %></td>
					<td>
						<% if item[:settled] %>
							已结算
						<% elsif can? :create, Settle %>
							<%= link_to "结算", set_settle_path(date: item[:date], scheme_id: item[:scheme].id), remote: "true", confirm: "确定已经结算完成？", method: "post", class: "link-settle" %>
						<% else %>
							未结算
						<% end %>
					</td>
				</tr>
			<% end %>
		<% else %>
			<tr>
			    <td colspan="4">没有数据</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/orders/show.html.erb
<% content_for :scripts do %>
	<%= javascript_include_tag "order-show" %>
<% end %>

<div class="row">
	<div class="span4">
		<table class="table table-striped">
			<caption>基本信息</caption>
			<tbody>
				<tr>
					<th>订单类型</th>
					<td><%= @order.category_desc %></td>
				</tr>
				<tr>
					<th>订单状态</th>
					<td><%= @order.status_desc %></td>
				</tr>
				<% unless @scheme.nil? %>
					<tr>
						<th>旅游线路</th>
						<td><%= link_to @scheme.name, scheme_path(@scheme) %></td>
					</tr>
				<% end %>
				<tr>
					<th>发团时间</th>
					<td><%= @order.tour_time %></td>
				</tr>
				<tr>
					<th>旅游人数</th>
					<td><%= @order.tour_members_count %></td>
				</tr>
				<tr>
					<th>免费儿童数</th>
					<td><%= @order.tour_children_free %></td>
				</tr>
				<tr>
					<th>半价儿童数</th>
					<td><%= @order.tour_children_discount %></td>
				</tr>
				<tr>
					<th>成人数</th>
					<td><%= @order.tour_adult_count %></td>
				</tr>
			</tbody>
		</table>
	</div>
	<% unless @hotel.nil? %>
	<div class="span4">
		<table class="table table-striped">
			<caption>酒店信息</caption>
			<tbody>
				<tr>
					<th>酒店名称</th>
					<td><%= @hotel.name %></td>
				</tr>
				<tr>
					<th>酒店地址</th>
					<td><%= @hotel.address %></td>
				</tr>
				<tr>
					<th>酒店电话</th>
					<td><%= @hotel.phone %></td>
				</tr>
			</tbody>
		</table>

	</div>
	<% end %>
	<% unless @flight.nil? %>
	<div class="span4">
		<table class="table table-striped">
			<caption>航班信息</caption>
			<tbody>
				<tr>
					<th>航班号</th>
					<td><%= @flight.number %></td>
				</tr>
				<tr>
					<th>航空公司</th>
					<td><%= @flight.airline %></td>
				</tr>
				<tr>
					<th>抵达时间</th>
					<td><%= @flight.arrive_at %></td>
				</tr>
			</tbody>
		</table>
	</div>
	<% end %>
</div>

<table class="table table-bordered">
	<caption>联系人信息</caption>
	<thead>
		<tr>
			<th>#</th>
			<th>姓名</th>
			<th>性别</th>
			<th>中国手机</th>
			<th>越南手机</th>
			<th>护照号</th>
			<th>qq</th>
			<th>微信</th>
			<th>微博</th>
			<th>邮箱</th>
		</tr>
	</thead>
	<tbody>
		<% @order.contacts.each_with_index do |contact, idx| %>
			<tr>
				<td><%= idx+1 %></td>
				<td><%= contact.name %></td>
				<td><%= contact.gender_desc %></td>
				<td><%= contact.chinese_phone %></td>
				<td><%= contact.vietnamese_phone %></td>
				<td><%= contact.passport_number %></td>
				<td><%= contact.qq %></td>
				<td><%= contact.wechat %></td>
				<td><%= contact.weibo %></td>
				<td><%= contact.email %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<% unless @order.cancel_reason.nil? %>
	<div class="well">订单取消原因: <%= @order.cancel_reason %></div>
<% end %>

<div class="row-fluid">
	<% if can? :update, @order %>
		<a href="<%= edit_order_path(@order) %>" class="btn btn-primary">
			<i class="icon-edit icon-white"></i> 编辑
		</a>
	<% end %>
	<% if can? :destroy, @order %>
		<a href="<%= destroy_order_path(@order) %>" data-method="delete" 
			data-confirm="确定要删除此订单?" data-disable-with="删除中..." 
			data-remote="true" class="btn btn-danger link-destroy-order">
			<i class="icon-remove icon-white"></i> 删除
		</a>
	<% end %>
	<%= link_to "返回", :back, class: "btn" %>
</div>