config/routes.rb
# -*- encoding : utf-8 -*-
Vietnam::Application.routes.draw do
  root :to => 'home#index'
  get "guides/index"
  get "about_us"      => 'home#about_us', as: :about_us
  get "contact_us"      => 'home#contact_us', as: :contact_us

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :areas, :cities, :albums, :schemes, :sights, :photos, :only => [:show]
  resources :experts, :homestays, only: [:index, :show]
  # resources :orders
  get '/infos', :to => 'infos#index'
  get '/infos/:id', :to => 'infos#show', as: :info
  get '/guides', :to => 'guides#index'
  # get '/girls', :to => 'home#girls', as: :girls
  # get '/girls/:id', :to => 'home#girl', as: :girl


  get 'orders/settle/'                => 'orders#settle', as: :settle_order
  post 'orders/settle/'              => 'orders#set_settle', as: :set_settle
  get 'orders/'                    =>  'orders#index'
  get 'orders/new/'                =>  'orders#new', as: :new_order
  get 'orders/new/pickup'          =>  'orders#new_pickup'
  get 'orders/new/tour'            =>  'orders#new_tour'
  post 'orders'                     =>  'orders#create'
  get 'orders/:id/'                 => 'orders#show',            as: :order
  get 'orders/:id/edit'             =>  'orders#edit',           as: :edit_order
  post 'orders/:id/'                => 'orders#update',          as: :update_order
  delete 'orders/:id/'              => 'orders#destroy',         as: :destroy_order

  get 'wedding'            => 'home#wedding', as: :wedding
  get 'tailor'             => 'home#tailor',  as: :tailor
  get 'charter'            => 'home#charter', as: :charter
end

app/models/city.rb
# -*- encoding : utf-8 -*-
class City < ActiveRecord::Base
  attr_accessible :name, :woeid, :desc, :area_id,
                  :content, :cover, :uuid, :prior, :has_experts, :has_homestays,
                  :route_info, :hotel_info, :traffic_info, :map

  belongs_to :area
  has_many :sights
  has_many :experts
  has_many :homestays

  mount_uploader :cover, PhotoUploader
  # mount_uploader :map, CityMapUploader

  validates :area_id, presence: true
  validates :name, presence: true
  #validates :cover, presence: true
  validates :uuid, :presence => true, :uniqueness => { case_sensitive: false }

  default_scope order('prior DESC')

  scope :has_experts, where(has_experts: true)
  scope :has_homestays, where(has_homestays: true)

  before_validation do
    if self.uuid.blank? # and self.new_record?
      write_attribute(:uuid, SecureRandom.uuid)
    end
    true
  end
end

# == Schema Information
#
# Table name: cities
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  desc         :text
#  woeid        :integer
#  area_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  content      :text
#  cover        :string(255)      not null
#  uuid         :string(255)      not null
#  weather      :text
#  route_info   :text
#  hotel_info   :text
#  traffic_info :text
#  map          :string(255)
#

app/controllers/cities_controller.rb
# -*- encoding : utf-8 -*-
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @area = @city.area
    @cities = @area.cities
    @areas = Area.all
    @sights = @city.sights
  end
end

app/helpers/cities_helper.rb
# -*- encoding : utf-8 -*-
module CitiesHelper
end

app/views/cities/show.html.erb
<% provide(:title, @city.name) %>

<% content_for :scripts do %>
	<%= javascript_include_tag "cities" %>
<% end %>

<div id="pg-city" class="container">
	<%= render 'layouts/header' %>

	<div class="content">
		<ul class="nav-area">
			<% @areas.each do |area| %>
			<li<%= " class=current" if area.eql? @area %>>
				<%= link_to area.name, area.cities.any?? city_path(area.cities.first) : '#' %>
			</li>
			<% end %>
		</ul>

		<div class="around">
			周边城市景点：
			<% @cities.each do |c| %>
				<%= link_to "#{ c.name }", city_path(c), class: ("current" if c.eql? @city) %>
			<% end %>
		</div>

		<div class="summary">
			<%= @city.weather.try(:html_safe) %>
			<%= image_tag @city.cover.pic, class: "cover", width: "560", height: "300" %>
			<p class="desc"><%= @city.desc %></p>
		</div>

		<% if @city.route_info %>
			<h4 class="section-title"><%= @city.name %>的最佳旅游时间</h4>
			<div class="route-info">
				<%= @city.route_info.html_safe %>
			</div>
		<% end %>

		<% if @city.hotel_info %>
			<h4 class="section-title"><%= @city.name %>的酒店信息</h4>
			<div class="hotel-info">
				<%= @city.hotel_info.html_safe %>
			</div>
		<% end %>

		<% if @city.traffic_info %>
			<h4 class="section-title"><%= @city.name %>的交通贴士</h4>
			<div class="traffic-info">
				<%= @city.traffic_info.html_safe %>
			</div>
		<% end %>

		<% if false and  @city.map %>
			<div class="map">
				<%= image_tag @city.map, width: "960", height: "300" %>
			</div>
		<% end %>

		<div class="sights">
			<h4 class="section-title"><%= @city.name %>的所有景点</h4>
			<% @sights.each do |s| %>
				<div class="sight">
					<%= link_to image_tag(s.cover.thumb, class: "cover", width: "300", height: "200"), sight_path(s) %>
					<h5><%= s.name %></h5>
					<div class="desc">
						<%= s.desc.truncate(200).html_safe %>
					</div>
					<%= link_to "查看景点详情", sight_path(s), class: "see" %>
				</div>
			<% end %>
		</div>
	</div>

	<%= render 'layouts/footer' %>
</div>