config/routes.rb
# -*- encoding : utf-8 -*-
Vietnam::Application.routes.draw do
  root :to => 'home#index'
  get "guides/index"
  get "about_us"      => 'home#about_us', as: :about_us
  get "contact_us"      => 'home#contact_us', as: :contact_us

  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :areas, :cities, :albums, :schemes, :sights, :photos, :only => [:show]
  resources :experts, :homestays, only: [:index, :show]
  # resources :orders
  get '/infos', :to => 'infos#index'
  get '/infos/:id', :to => 'infos#show', as: :info
  get '/guides', :to => 'guides#index'
  # get '/girls', :to => 'home#girls', as: :girls
  # get '/girls/:id', :to => 'home#girl', as: :girl


  get 'orders/settle/'                => 'orders#settle', as: :settle_order
  post 'orders/settle/'              => 'orders#set_settle', as: :set_settle
  get 'orders/'                    =>  'orders#index'
  get 'orders/new/'                =>  'orders#new', as: :new_order
  get 'orders/new/pickup'          =>  'orders#new_pickup'
  get 'orders/new/tour'            =>  'orders#new_tour'
  post 'orders'                     =>  'orders#create'
  get 'orders/:id/'                 => 'orders#show',            as: :order
  get 'orders/:id/edit'             =>  'orders#edit',           as: :edit_order
  post 'orders/:id/'                => 'orders#update',          as: :update_order
  delete 'orders/:id/'              => 'orders#destroy',         as: :destroy_order

  get 'wedding'            => 'home#wedding', as: :wedding
  get 'tailor'             => 'home#tailor',  as: :tailor
  get 'charter'            => 'home#charter', as: :charter
end

app/views/layouts/_admin_header.html.erb
<div class="header">
	<h1 class="logo">行在越南 - 订单管理系统</h1>

	<div class="user-links">
		<div class="btn-group">
			<%= link_to "订单列表", orders_path, class: "btn" %>
			<% if current_admin_user.admin? or current_admin_user.superuser? or current_admin_user.agency? %>
				<%= link_to "订单结算", settle_order_path, class: "btn link-settel" %>
			<% end %>
			<% if can? :create, Order %>
				<%= link_to "创建订单", new_order_path, class: "btn link-new-order" %>
			<% end %>
			<% if can? :manage, :all %>
				<%= link_to "回到后台", admin_areas_path, class: "btn link-back-activeadmin" %>
			<% end %>
		</div>
		<div class="btn-group">
			<%= link_to "退出登录", destroy_admin_user_session_path, class: "btn btn-danger link-logout" %>
		</div>
	</div>
</div>

app/views/layouts/_contact_qqs.html.erb
<div class="contact-qqs">
	<span>免费咨询</span>
	<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2055086388&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:2055086388:51" alt="给2055086388发消息" title="给2055086388发消息"/></a>
	<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2967052963&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:2967052963:51" alt="给2967052963发消息" title="给2967052963发消息"/></a>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<a href="http://e.weibo.com/u/3770998044" target="_blank" class="link-weibo">新浪官方微博</a>
	<ul class="nav">
		<%= nav_link_to "关于我们", about_us_path %>
		<%= nav_link_to "联系我们", contact_us_path %>
	</ul>
	<%# render "layouts/contact_qqs" %>
	<p class="copyright">Copyright &copy;2013-2014 行在越南 All Rights Reserved. <br /><a href="http://www.miitbeian.gov.cn/" target="_blank">蜀ICP备13016263号</a></p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
	<h1 class="logo"><%= link_to '行在越南', root_path %></h1>
	<ul class="nav">
		<%= nav_link_to "首页", root_path %>
		<%= nav_link_to "旅游线路", scheme_nav_path %>
		<%= nav_link_to "旅游景点", sight_nav_path %>
		<%# nav_link_to "旅游婚纱", wedding_path %>
		<%# nav_link_to "奥黛定做", tailor_path %>
		<%# nav_link_to "VIP包车旅游", charter_path %>
		<%= nav_link_to "旅游手册", guides_path %>
		<%= nav_link_to "旅游攻略", infos_path %>
		<%= nav_link_to "越南导游", experts_path %>
		<%= nav_link_to "家庭旅馆", homestays_path %>
		<%= nav_link_to "论坛BBS", "http://bbs.zouba123.com/" %>
		<%# nav_link_to "越南美女图库", girls_path %>
		<%# nav_link_to "关于我们", about_us_path %>
		<%# nav_link_to "联系我们", contact_us_path %>
	</ul>

	<div class="share">
		分享：<%= social_share_button_tag("行在越南网最专业的越南背包自由行和包车旅游网站，行在越南，心在越南", url: "http://#{ Yetting.domain }/") %>
	</div>
</div>

app/views/layouts/_slides.html.erb
<div id="slides" class="slides">
	<div class="slides-list">
		<div class="slide">
			<%= link_to image_tag(@slide_photo.file.url), @slide_photo.link, targe: "_blank" %>
			<div class="caption">
				<h5><%= @slide_photo.name %></h5>
				<p><%= @slide_photo.desc %></p>
			</div>
		</div>
	</div>
	<% if false %>
	<a class="prev" href="javascript:;">&lsaquo;</a>
	<a class="next" href="javascript:;">&rsaquo;</a>
	<% end %>
</div>

app/views/layouts/_totango.html.erb
<!-- Totango Tracking Code -->
<script>
var totango_options = {
  service_id: "SP-6918-01",                  // Your unique Totango service id is SP-6918-01. Don't change this.
  username: "wls860801@gmail.com",             // replace with the tracked user's email or unique id.
  account:                                  // An account can have multiple users (usually in B2B).
  {
	id: "vietnam",                         // replace with the tracked account's unique id.
	name: "zouba123",                      // replace with the tracked account's account display name.
	status: "Free",                           // or "paying".
	"Create Date": "2013-12-12T19:25:58.0Z"   // Optional - The date that the tracked account was created.
  }
  // For more options and examples see http://help.totango.com/developers/
};

window.totango = {go: function(){return -1}, track: function(){}, identify: function(){}, setAccountAttributes: function(){}};
(function() {
var e = document.createElement('script'); e.type = 'text/javascript'; e.async = true;
e.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 's3.amazonaws.com/totango-cdn/totango2.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(e, s);
})();
</script>
<!-- End Totango Tracking Code -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) + ' - ' if content_for?(:title) %>大爱西贡</title>
	<link rel="shortcut icon" href="/favicon.ico" />
	<%= stylesheet_link_tag    "admin", :media => "all" %>
	<%= yield :styles %>
	<%= csrf_meta_tags %>
</head>
<body class="active-admin">
	<div class="container-fluid">
		<%= render 'layouts/admin_header' %>
		<%= yield %>
	</div>

	<%= javascript_include_tag "admin" %>
	<%= yield :scripts %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) + ' - ' if content_for?(:title) %>行在越南</title>
  <meta name="description" content="行在越南网最专业的越南背包自由行攻略网站" />
  <meta name="keywords" content="越南旅游,越南旅行社,越南旅游攻略,越南自助游,行在越南,行在越南网,岘港旅游,越南美女" />
  <meta property="wb:webmaster" content="ae1a6f8eab859c5c" />
  <link rel="shortcut icon" href="/favicon.ico" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38514007-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>
  <%= render "layouts/totango" %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <%= yield %>

  <%= javascript_include_tag "application" %>
  <%= yield :scripts %>
</body>
</html>